### ISSUE TITLE
can't found internal.h

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [munhyunsu/PidginPluginLOLChat#1]
Where I can found internal.h in order to compile the shared library?

**Comment by munhyunsu** [comment]
Hi Alessandro-Barbieri.
it is pidgin library. so, you can get it in pidgin source dir.
(https://developer.pidgin.im/wiki/CHowTo/BasicPluginHowto)

**Comment by Alessandro-Barbieri** [comment]
There is no reference in the guide of that header and is not present in debian source packages

https://packages.debian.org/jessie/all/pidgin-dev/filelist
https://packages.debian.org/jessie/all/libpurple-dev/filelist

it seems a private header https://pidgin.im/pipermail/devel/2008-September/018384.html

**Comment by munhyunsu** [comment]
1) download pidgin-source tar
2) extract tar (ex. pidgin-2.10.11)
3) change directory to ./pidgin/libpurple/ (ex. cd pidgin-2.10.11/libpurple/)
4) in there(libpurple), internal.h is placed.

**Comment by Alessandro-Barbieri** [comment]
I'm trying to compile without that
from this reference
https://developer.pidgin.im/doxygen/2.0.0/html/internal_8h.html
seems you are using it only for N_()

Can you confirm you are using that header only for the function N_()?

**Comment by munhyunsu** [comment]
yes, i use N_() for 
source code version 1.01b line 47. 
#define LC_PLUGIN_DESCRIPTION N_("League of Legends Chatting Plugin.\nThis plugin makes User infomation more comport.")

it is open source. so you can modify source and using it. :D 
if you want push to 1.01b. i do. for more efficient plugin.
thanks for your attention.
